# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mybuf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mybuf.proto',
  package='hw1',
  serialized_pb=_b('\n\x0bmybuf.proto\x12\x03hw1\"!\n\x04Pack\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03msg\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PACK = _descriptor.Descriptor(
  name='Pack',
  full_name='hw1.Pack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hw1.Pack.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='hw1.Pack.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['Pack'] = _PACK

Pack = _reflection.GeneratedProtocolMessageType('Pack', (_message.Message,), dict(
  DESCRIPTOR = _PACK,
  __module__ = 'mybuf_pb2'
  # @@protoc_insertion_point(class_scope:hw1.Pack)
  ))
_sym_db.RegisterMessage(Pack)


# @@protoc_insertion_point(module_scope)
