# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mybuf21.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mybuf21.proto',
  package='hw21',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rmybuf21.proto\x12\x04hw21\"!\n\x04Pack\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03msg\x18\x02 \x02(\t')
)




_PACK = _descriptor.Descriptor(
  name='Pack',
  full_name='hw21.Pack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='hw21.Pack.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='hw21.Pack.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=56,
)

DESCRIPTOR.message_types_by_name['Pack'] = _PACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pack = _reflection.GeneratedProtocolMessageType('Pack', (_message.Message,), {
  'DESCRIPTOR' : _PACK,
  '__module__' : 'mybuf21_pb2'
  # @@protoc_insertion_point(class_scope:hw21.Pack)
  })
_sym_db.RegisterMessage(Pack)


# @@protoc_insertion_point(module_scope)
